# Generated by Django 3.2.5 on 2023-10-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
    ]
