# Generated by Django 3.2.5 on 2023-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_appointment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('rechargeType', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=50)),
            ],
        ),
    ]
