# Generated by Django 3.2.5 on 2023-10-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
