# Generated by Django 3.2.5 on 2023-11-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
