# Generated by Django 3.2.5 on 2023-11-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_user_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
